name: Daily GenAI KPI scrape

on:
  schedule:
    - cron: '0 5 * * *'   # 05:00 UTC daily
  workflow_dispatch:       # manual run button

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute scraper
        run: python scraper.py

      - name: Commit & push if data changed
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add *.csv
          git diff --cached --quiet || git commit -m " $(date -u +'%Y-%m-%d') update"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
